steps:
- uses: actions/checkout@latest
- uses: actions/setup-java@v1
  with:
    java-version: 1.8
- uses: DeLaGuardo/setup-clojure@2.0
  with:
    lein: 2.9.1
- run: lein with-profile clj-1.8.0 test && lein with-profile clj-1.9.0 test && lein with-profile clj-1.10.0 test
