on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: DeLaGuardo/setup-clojure@2.0
      with:
        lein: 2.9.1
    - run: ls
    - run: lein with-profile clj-1.8.0 test && lein with-profile clj-1.9.0 test && lein with-profile clj-1.10.0 test
